build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Bhardwaj, Tanu"
    email: "bhardwaj.tanu@xyz.com"
  onCallSupport:
    - (+91) 12345-6789
    - (+91) 98765-4321
